language: go

os: linux
dist: xenial

go:
  - "1.14"

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - "mkdir -p release"
  - "GOOS=linux  GOARCH=amd64 go build -o release/powerline-go-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o release/powerline-go-darwin-amd64"
  - "GOOS=windows GOARCH=amd64 go build -o release/powerline-go-windows-amd64"
  - "GOOS=openbsd GOARCH=amd64 go build -o release/powerline-go-openbsd-amd64"
  - "GOOS=freebsd GOARCH=amd64 go build -o release/powerline-go-freebsd-amd64"

deploy:
  provider: releases
  api_key:
    secure: OA/pzHmOxhimxGvcTuLdBXc4g/cAJTKCJcvMSXFTp6pIYTxOaiLR11r4mGJSHkILCQWjRHxBTUzy5XDja9jqkApgpTaAMmuDZrJJstN4yryxBTRee25uaTc02sPiTgCyDo8MnQJ36C3+5A2T+D0yTLWGAiXLrGYrZCN+plnQfC6uVeLGWXQ5CaqNOwxZ62KSxGLHfkVR44MVFYZVJqXlMoSEYUlAqZ7Q3fqdzZFtsR9ErGg22W/faVyT/R6Lkr9rpJUFWupU71GhNeCcKkpIbv1EcDN3BEVfSmgKpxNq1fQ8ajgfkEfARUoFv3DjYAo5260CGgTXCYWaH1qFZRP/zUT+Hk4Eo8R8a8aCPwbwO0mBuQ5B8DljWLE7JO+cvSPCLEZEGvdrUEMODE60/WYsJhW6ljFxY57yzZXXhgi7cFGgauwu5SyhL8zMfZBFXADx7CAWgIwmwGaX9T/iKSH3sxsfKNbVsYvVmu2oxNbykXSxrLD4a/qb1bWOKiTvs7lN+Y3iRWNqUfzu5tiTPHiOl6+AYHtm3ZpC1uaPVpopGaMnReH/Q194GsqVCOjMkLuYAV1eu9Y4mbdxnVnYYJT4Lic7TSALQ2q88fEP4MuzA5BkgVgtPf+XDHQmFBxOdEa8LwllBPUr8wfAQBP1ZkjQyPl77l1Ktt1bsAysv++1bZA=
  file:
    - "release/powerline-go-linux-amd64"
    - "release/powerline-go-darwin-amd64"
    - "release/powerline-go-windows-amd64"
    - "release/powerline-go-openbsd-amd64"
    - "release/powerline-go-freebsd-amd64"
  skip_cleanup: true
  on:
    tags: true
    repo: justjanne/powerline-go
