sudo: false
language: go

go:
  - 1.10
before_script:
  - go get

# before we deploy, we go build for all operating systems we would like to support
before_deploy:
  - mkdir -p release
  - "GOOS=linux  GOARCH=amd64 go build -o release/powerline-go-linux-amd64"
  - "GOOS=darwin GOARCH=amd64 go build -o release/powerline-go-darwin-amd64"
# Windows doesn't work yet, due to the readonly segment
#  - "GOOS=windows GOARCH=amd64 go build -o release/powerline-go-windows-amd64"

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_API_KEY"
  file:
    - "release/powerline-go-linux-amd64"
    - "release/powerline-go-darwin-amd64"
# Windows doesn't work yet, due to the readonly segment
#    - "release/powerline-go-windows-amd64"
  skip_cleanup: true
  on:
    tags: true
